//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kimlik
    {
        public int KimlikId { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string LogoURL { get; set; }
        public string Ünvan { get; set; }
    }
}
